Example Sign:
  world: world
  coordinate: 0, 0, 0
  level-cost: 3
  items: potion:instant_heal:3, golden_apple:2
Random Sign:
  world: world
  coordinate: 1, 0, 0
  level-cost: 1
  hard-pity-outcome: outcome1
  items:
    outcome1:
      items: potion:instant_heal, golden_apple:2
      prob: 0.1
    outcome2:
      items: golden_apple
      prob: 0.9
Clear Inventory Sign:
  world: world
  coordinate: 2, 0, 0
  level-cost: 0
  clear-inventory: true